project:
  type: website

website:
  title: "DSAN-5000: Project"
  navbar:
    left:
      - href: index.qmd
      - href: about.ipynb
        text: About
      - href: introduction/introduction.ipynb
        text: Introduction
      - href: https://github.com/anly501/dsan-5000-project-mattycars
        text: Code
      - href: https://github.com/anly501/dsan-5000-project-mattycars/tree/main/data
        text: Data
      - href: gathering/gathering.ipynb
        text: Data Gathering
      - text: Data Cleaning
        menu: 
          - cleaning/cleaning.rmd
          - cleaning/text.ipynb
      - href: eda/eda.rmd
        text: Data Exploration
      - text: Naive Bayes Classification
        menu: 
          - NaiveBayes/NaiveBayesIntro.qmd
          - NaiveBayes/NB_categorical_classifier.ipynb
          - NaiveBayes/NB_text_classifier.ipynb
      - href: dimensionality/dimensionality.ipynb
        text: Dimensionality Reduction
      - href: clustering/clustering.ipynb
        text: Clustering
      - href: trees/classification.ipynb    
        text: Classifying Podium Finishers
      - href: conclusions/conclusions.ipynb
        text: Conclusions
format:
  html:
    theme: cosmo
    toc: true



